import 'dart:io';
import 'dart:typed_data';

import 'package:path/path.dart' as p;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../data/models/ecg_record_model.dart';
import 'dr_cardio_storage.dart';
import 'ecg/ecg_data.dart';
import 'record_file_naming.dart';
import 'storage_service.dart';

/// A from-scratch redesign of the report layout, replacing
/// `SupportClass.PdfGenerator` (1,379 lines of manual `Canvas`/`Paint`
/// pixel-position drawing — the source of the "outdated, misaligned"
/// report the client flagged). This version builds the page with the
/// `pdf` package's layout widgets (`pw.Table`, `pw.Row`/`Column`, `Expanded`)
/// so spacing and alignment are computed for us instead of hand-placed
/// x/y coordinates, and lays out cleanly regardless of name/label length.
class PdfReportService {
  PdfReportService._();

  static final _headerColor = PdfColor.fromHex('#C53827');
  static final _inkColor = PdfColor.fromHex('#201F1E');
  static final _mutedColor = PdfColor.fromHex('#6B6B6B');
  static final _borderColor = PdfColor.fromHex('#E5E5E5');

  static Future<File> generate(EcgRecordModel record) async {
    final storage = StorageService.instance;
    final doc = pw.Document();
    final reportTypes = storage.reportTypes.isEmpty ? const ['Simultaneous 4x3'] : storage.reportTypes;

    // Read once up front (the only async step) rather than per report-type
    // page — every `_build*` method below stays synchronous. Port of
    // `PdfGenerator`'s non-empty-string-checked `patient_photo`/
    // `patient_signature_photo` draws: null here (empty path, or the file
    // no longer exists) means the page reserves no space for it at all,
    // not an empty box.
    final photoImage = await _loadImage(record.patient.photoPath);
    final signatureImage = await _loadImage(record.patient.signaturePath);

    doc.addPage(
      pw.MultiPage(
        // The live app's report (`PdfGenerator`, `R.integer.report_page_width/
        // height`) is landscape A4 (842x595pt) — matching this matters for
        // printing/scanning into a patient file sized for that orientation,
        // not just cosmetics.
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.all(28),
        header: (context) => _buildLetterhead(storage),
        // Port of `PdfGenerator.generatePDF()`'s loop over
        // `settings.reportTypes`/`settings.reports[i]` — one page per
        // selected report type, appended to the same document.
        build: (context) => [
          for (var i = 0; i < reportTypes.length; i++) ...[
            if (i > 0) pw.NewPage(),
            ..._buildReportPage(record, storage, reportTypes[i], photoImage, signatureImage),
          ],
        ],
        footer: (context) => pw.Column(
          children: [
            pw.Divider(color: _borderColor),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Generated by Dr. Cardio ECG', style: pw.TextStyle(fontSize: 7, color: _mutedColor)),
                pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: pw.TextStyle(fontSize: 7, color: _mutedColor)),
              ],
            ),
          ],
        ),
      ),
    );

    final dir = await DrCardioStorage.reportsDir();
    final file = File(p.join(dir.path, '${RecordFileNaming.stem(record)}.pdf'));
    await file.writeAsBytes(await doc.save());
    return file;
  }

  /// Port of `PdfGenerator.getReportPage()`'s switch over reportType: grid
  /// shape and column count come from the "NxM" name — 6x2 → 2 columns of 6,
  /// 12x1 → 1 column of 12, else (4x3) → **4** columns of **3** — matching
  /// `draw4x3Graphs()`'s `rows = 3` (fixed by the page's available height /
  /// `y_boxes`), which groups leads I/II/III, aVR/aVL/aVF, V1/V2/V3,
  /// V4/V5/V6 one clinical group per column. (An earlier version of this
  /// port had this backwards — 3 columns of 4 — which split each column
  /// across two different lead groups instead of keeping one per column.)
  /// "Simultaneous" vs "Sequential" decides whether every column shows the
  /// same time window or each one a later slice of the recording — same
  /// as the original's `data_start = simultaneous ? 0 : floor(ch/rows) *
  /// graph_duration`. Only the 4x3 layouts get the extra full-width long
  /// lead strip, matching `draw4x3Graphs()`'s dedicated final row (6x2 and
  /// 12x1 have no equivalent in the original).
  static List<pw.Widget> _buildReportPage(
    EcgRecordModel record,
    StorageService storage,
    String reportType,
    pw.MemoryImage? photoImage,
    pw.MemoryImage? signatureImage,
  ) {
    final simultaneous = reportType.startsWith('Simultaneous');
    final int columns;
    final int rowsPerColumn;
    if (reportType.contains('6x2')) {
      columns = 2;
      rowsPerColumn = 6;
    } else if (reportType == '12x1') {
      columns = 1;
      rowsPerColumn = 12;
    } else {
      columns = 4;
      rowsPerColumn = 3;
    }

    final analysisStrip = _buildAnalysisStrip(record);

    return [
      pw.SizedBox(height: 10),
      _buildPatientInfoTable(record, photoImage),
      if (analysisStrip != null) ...[
        pw.SizedBox(height: 8),
        analysisStrip,
      ],
      pw.SizedBox(height: 14),
      pw.Text('12-LEAD ECG — ${reportType.toUpperCase()}', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _headerColor)),
      pw.SizedBox(height: 6),
      _buildLeadGrid(record, columns: columns, rowsPerColumn: rowsPerColumn, simultaneous: simultaneous),
      if (reportType.contains('4x3')) ...[
        pw.SizedBox(height: 14),
        pw.Text('RHYTHM STRIP — LEAD ${storage.longLead}', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _headerColor)),
        pw.SizedBox(height: 6),
        _buildRhythmStrip(record, storage.longLead),
      ],
      if (signatureImage != null) ...[
        pw.SizedBox(height: 14),
        _buildSignatureBlock(signatureImage),
      ],
      pw.SizedBox(height: 16),
      _buildCalibrationFooter(record, storage),
    ];
  }

  static pw.Widget _buildLetterhead(StorageService storage) {
    return pw.Column(
      children: [
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.Container(width: 34, height: 34, decoration: pw.BoxDecoration(color: _headerColor, shape: pw.BoxShape.circle)),
            pw.SizedBox(width: 10),
            pw.Expanded(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Dr. Cardio', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: _headerColor)),
                  pw.Text(
                    storage.clinicName.isEmpty ? 'ECG in your pocket' : storage.clinicName,
                    style: pw.TextStyle(fontSize: 8.5, color: _mutedColor),
                  ),
                ],
              ),
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text('12-Lead ECG Report', style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: _inkColor)),
                pw.Text(_formatDate(DateTime.now()), style: pw.TextStyle(fontSize: 8, color: _mutedColor)),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Container(height: 2, color: _headerColor),
      ],
    );
  }

  static pw.Widget _infoField(String label, String value) => pw.Expanded(
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(label, style: pw.TextStyle(fontSize: 7, color: _mutedColor)),
            pw.SizedBox(height: 2),
            pw.Text(value.isEmpty ? '—' : value, style: pw.TextStyle(fontSize: 9.5, fontWeight: pw.FontWeight.bold, color: _inkColor)),
          ],
        ),
      );

  static pw.Widget _buildPatientInfoTable(EcgRecordModel record, pw.MemoryImage? photoImage) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(border: pw.Border.all(color: _borderColor), borderRadius: pw.BorderRadius.circular(6)),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              children: [
                pw.Row(children: [
                  _infoField('PATIENT', record.patient.name),
                  _infoField('ID', record.patient.patientId),
                  _infoField('AGE / SEX', '${record.patient.age} / ${record.patient.sex}'),
                ]),
                pw.SizedBox(height: 8),
                pw.Row(children: [
                  _infoField('RECORDED', _formatDate(record.dateTime)),
                  _infoField('DEVICE', record.deviceName.isEmpty ? '—' : record.deviceName),
                  _infoField('HEART RATE', record.hr.isEmpty ? '—' : '${record.hr} bpm'),
                ]),
              ],
            ),
          ),
          // Port of `PdfGenerator.drawPatientPhotoInfo()` — a small
          // passport-style thumbnail, only reserved when a photo was
          // actually captured (see [_loadImage]'s null-on-missing rule).
          if (photoImage != null) ...[
            pw.SizedBox(width: 10),
            pw.Container(
              width: 42,
              height: 42,
              decoration: pw.BoxDecoration(border: pw.Border.all(color: _borderColor, width: 0.6), borderRadius: pw.BorderRadius.circular(4)),
              child: pw.ClipRRect(
                horizontalRadius: 4,
                verticalRadius: 4,
                child: pw.Image(photoImage, fit: pw.BoxFit.cover),
              ),
            ),
          ],
        ],
      ),
    );
  }

  /// Port of `PdfGenerator.getEcgAnalysis()`'s HR/R(II)/RR/PR/QRS/QT/QTc/
  /// QT-QTc line — all eight figures the device computes from the
  /// recording (via `EcgAnalysisService`, run once at save time). Omitted
  /// entirely (not drawn as a row of dashes) when [EcgRecordModel.hr] is
  /// empty — a recording under ~13s, or one saved before this measurement
  /// existed, simply has nothing to show here rather than misleading blanks
  /// dressed up as a table.
  static pw.Widget? _buildAnalysisStrip(EcgRecordModel record) {
    if (record.hr.isEmpty) return null;
    final items = <MapEntry<String, String>>[
      MapEntry('HR', '${record.hr}/min'),
      MapEntry('R(II)', '${record.r}mV'),
      MapEntry('RR', '${record.rr}ms'),
      MapEntry('PR', '${record.pr}ms'),
      MapEntry('QRS', '${record.qrs}ms'),
      MapEntry('QT', '${record.qt}ms'),
      MapEntry('QTc', '${record.qtc}ms'),
      MapEntry('QT/QTc', record.qtByQtc),
    ];
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 8),
      decoration: pw.BoxDecoration(border: pw.Border.all(color: _borderColor), borderRadius: pw.BorderRadius.circular(6)),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: items
            .map((e) => pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(e.key, style: pw.TextStyle(fontSize: 6.5, fontWeight: pw.FontWeight.bold, color: _mutedColor)),
                    pw.SizedBox(height: 2),
                    pw.Text(e.value, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: _inkColor)),
                  ],
                ))
            .toList(),
      ),
    );
  }

  /// Right-aligned signature line + caption, placed after the lead
  /// grid/rhythm strip — port of `PdfGenerator.drawPatientSignatureInfo()`,
  /// minus its "Patient Sign" caption being unconditional text unrelated to
  /// whether an image was actually captured (a copy-paste leftover flagged
  /// during research, not worth reproducing): here the whole block only
  /// exists when [signatureImage] is non-null.
  static pw.Widget _buildSignatureBlock(pw.MemoryImage signatureImage) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.end,
      children: [
        pw.Column(
          children: [
            pw.Container(
              width: 100,
              height: 30,
              alignment: pw.Alignment.bottomCenter,
              padding: const pw.EdgeInsets.only(bottom: 2),
              decoration: pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: _borderColor, width: 0.8))),
              child: pw.Image(signatureImage, fit: pw.BoxFit.contain, height: 26),
            ),
            pw.SizedBox(height: 3),
            pw.Text('PATIENT SIGNATURE', style: pw.TextStyle(fontSize: 6, fontWeight: pw.FontWeight.bold, color: _mutedColor)),
          ],
        ),
      ],
    );
  }

  /// Empty path, missing file, or an unreadable one all resolve to null —
  /// the caller treats null as "nothing to draw", not a placeholder.
  static Future<pw.MemoryImage?> _loadImage(String path) async {
    if (path.isEmpty) return null;
    final file = File(path);
    if (!await file.exists()) return null;
    try {
      final bytes = await file.readAsBytes();
      return pw.MemoryImage(bytes);
    } catch (_) {
      return null;
    }
  }

  /// [columns]/[rowsPerColumn] shape the grid ([columns] * [rowsPerColumn]
  /// must be 12); leads fill column-major (column 0 gets leads
  /// 0..rowsPerColumn-1, matching the original's `column = floor(ch /
  /// rows)`) so a 4x3 report reads the standard clinical way — limb leads,
  /// then augmented, then chest — rather than row-major. When not
  /// [simultaneous], each column plots a later slice of the recording
  /// instead of all columns sharing the same (latest) window.
  static pw.Widget _buildLeadGrid(EcgRecordModel record, {required int columns, required int rowsPerColumn, required bool simultaneous}) {
    final cellHeight = rowsPerColumn > 6 ? 34.0 : (rowsPerColumn > 4 ? 40.0 : 46.0);
    final columnWidgets = <pw.Widget>[];
    for (var col = 0; col < columns; col++) {
      final cells = <pw.Widget>[];
      for (var row = 0; row < rowsPerColumn; row++) {
        final index = col * rowsPerColumn + row;
        final leadName = index < EcgData.leadName.length ? EcgData.leadName[index] : '';
        final full = index < record.leadData.length ? record.leadData[index] : const <double>[];
        final samples = simultaneous ? full : _sequentialSlice(full, columns, col);
        cells.add(pw.Container(
          margin: const pw.EdgeInsets.all(2),
          height: cellHeight,
          decoration: pw.BoxDecoration(border: pw.Border.all(color: _borderColor, width: 0.5)),
          child: pw.Stack(children: [
            pw.Positioned(top: 2, left: 3, child: pw.Text(leadName, style: pw.TextStyle(fontSize: 6, color: _mutedColor))),
            // Scaled to roughly fill each column's share of the (now
            // landscape, so wider) page rather than a single width for
            // every layout — a 4-column report's cells are narrower than a
            // 2-column one's.
            pw.Center(child: _tracePainter(samples, width: columns == 1 ? 700 : 720 / columns, height: cellHeight - 6)),
          ]),
        ));
      }
      columnWidgets.add(pw.Expanded(child: pw.Column(children: cells)));
    }
    return pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: columnWidgets);
  }

  /// Splits [samples] into [columns] equal contiguous chunks and returns
  /// the one for [columnIndex] — port of the original's per-column
  /// `data_start` offset for a "Sequential" report, approximated here as
  /// dividing the recording into as many time segments as there are
  /// columns rather than a fixed on-device `graph_duration`, since this
  /// app's samples are already down-sampled to a fixed count rather than a
  /// raw, device-clock-timed stream.
  static List<double> _sequentialSlice(List<double> samples, int columns, int columnIndex) {
    if (samples.isEmpty || columns <= 1) return samples;
    final chunk = samples.length ~/ columns;
    if (chunk == 0) return samples;
    final start = columnIndex * chunk;
    final end = columnIndex == columns - 1 ? samples.length : start + chunk;
    return samples.sublist(start, end);
  }

  static pw.Widget _buildRhythmStrip(EcgRecordModel record, String longLead) {
    // Port of `PdfGenerator`'s `ECGLeads.getLeadIndex(PrefHelper.getString
    // ("SelectedLongLead", "II"))` — falls back to Lead II (index 1) both
    // when the stored name isn't found and via the same "II" default the
    // preference itself uses.
    final index = EcgData.leadName.indexOf(longLead);
    final leadIndex = index == -1 ? 1 : index;
    final samples = leadIndex < record.leadData.length ? record.leadData[leadIndex] : const <double>[];
    return pw.Container(
      height: 60,
      decoration: pw.BoxDecoration(border: pw.Border.all(color: _borderColor, width: 0.5)),
      child: pw.Center(child: _tracePainter(samples, width: 520, height: 54)),
    );
  }

  /// Port of the original report's fixed bottom-of-page line — every page
  /// carries "To be Finally Confirmed by the doctor" / "Software calculated
  /// values. To be verified manually" regardless of report type, since the
  /// values above (HR, QT, QTc, etc.) are device-computed, not a
  /// cardiologist's read.
  static pw.Widget _buildCalibrationFooter(EcgRecordModel record, StorageService storage) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Expanded(
          child: pw.Text(
            '${storage.xAxisScale} mm/s · 10 mm/mV · ${record.filter}',
            style: pw.TextStyle(fontSize: 8, color: _mutedColor),
          ),
        ),
        pw.Expanded(
          child: pw.Column(
            children: [
              pw.Text(
                'To be Finally Confirmed by the doctor',
                textAlign: pw.TextAlign.center,
                style: pw.TextStyle(fontSize: 7.5, fontWeight: pw.FontWeight.bold, color: _inkColor),
              ),
              pw.Text(
                'Software calculated values. To be verified manually',
                textAlign: pw.TextAlign.center,
                style: pw.TextStyle(fontSize: 7, color: _mutedColor),
              ),
            ],
          ),
        ),
        pw.Expanded(
          child: pw.Text('Gain: ${record.gain}', textAlign: pw.TextAlign.right, style: pw.TextStyle(fontSize: 8, color: _mutedColor)),
        ),
      ],
    );
  }

  static pw.Widget _tracePainter(List<double> samples, {required double width, required double height}) {
    return pw.CustomPaint(
      size: PdfPoint(width, height),
      painter: (context, size) {
        if (samples.isEmpty) return;
        final midY = size.y / 2;
        final window = samples.length > 300 ? samples.sublist(samples.length - 300) : samples;
        final xScale = size.x / window.length;
        context.setStrokeColor(_inkColor);
        context.setLineWidth(0.6);
        context.moveTo(0, midY - window[0] * 14);
        for (var i = 1; i < window.length; i++) {
          context.lineTo(i * xScale, midY - window[i] * 14);
        }
        context.strokePath();
      },
    );
  }

  static String _formatDate(DateTime dt) {
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return '${dt.day} ${months[dt.month - 1]} ${dt.year}, ${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}';
  }
}
