import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../data/models/ecg_record_model.dart';
import 'ecg/ecg_data.dart';
import 'storage_service.dart';

/// A from-scratch redesign of the report layout, replacing
/// `SupportClass.PdfGenerator` (1,379 lines of manual `Canvas`/`Paint`
/// pixel-position drawing — the source of the "outdated, misaligned"
/// report the client flagged). This version builds the page with the
/// `pdf` package's layout widgets (`pw.Table`, `pw.Row`/`Column`, `Expanded`)
/// so spacing and alignment are computed for us instead of hand-placed
/// x/y coordinates, and lays out cleanly regardless of name/label length.
class PdfReportService {
  PdfReportService._();

  static final _headerColor = PdfColor.fromHex('#C53827');
  static final _inkColor = PdfColor.fromHex('#201F1E');
  static final _mutedColor = PdfColor.fromHex('#6B6B6B');
  static final _borderColor = PdfColor.fromHex('#E5E5E5');

  static Future<File> generate(EcgRecordModel record) async {
    final storage = StorageService.instance;
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        header: (context) => _buildLetterhead(storage),
        build: (context) => [
          pw.SizedBox(height: 10),
          _buildPatientInfoTable(record),
          pw.SizedBox(height: 14),
          pw.Text('12-LEAD ECG', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _headerColor)),
          pw.SizedBox(height: 6),
          _buildLeadGrid(record),
          pw.SizedBox(height: 14),
          pw.Text('RHYTHM STRIP — LEAD II', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _headerColor)),
          pw.SizedBox(height: 6),
          _buildRhythmStrip(record),
          pw.SizedBox(height: 16),
          _buildCalibrationFooter(record, storage),
        ],
        footer: (context) => pw.Column(
          children: [
            pw.Divider(color: _borderColor),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Generated by Dr. Cardio ECG', style: pw.TextStyle(fontSize: 7, color: _mutedColor)),
                pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: pw.TextStyle(fontSize: 7, color: _mutedColor)),
              ],
            ),
          ],
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final reportsDir = Directory(p.join(dir.path, 'ecg_reports'));
    if (!await reportsDir.exists()) await reportsDir.create(recursive: true);
    final file = File(p.join(reportsDir.path, '${record.id}.pdf'));
    await file.writeAsBytes(await doc.save());
    return file;
  }

  static pw.Widget _buildLetterhead(StorageService storage) {
    return pw.Column(
      children: [
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.Container(width: 34, height: 34, decoration: pw.BoxDecoration(color: _headerColor, shape: pw.BoxShape.circle)),
            pw.SizedBox(width: 10),
            pw.Expanded(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Dr. Cardio', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: _headerColor)),
                  pw.Text(
                    storage.clinicName.isEmpty ? 'ECG in your pocket' : storage.clinicName,
                    style: pw.TextStyle(fontSize: 8.5, color: _mutedColor),
                  ),
                ],
              ),
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text('12-Lead ECG Report', style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: _inkColor)),
                pw.Text(_formatDate(DateTime.now()), style: pw.TextStyle(fontSize: 8, color: _mutedColor)),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Container(height: 2, color: _headerColor),
      ],
    );
  }

  static pw.Widget _infoField(String label, String value) => pw.Expanded(
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(label, style: pw.TextStyle(fontSize: 7, color: _mutedColor)),
            pw.SizedBox(height: 2),
            pw.Text(value.isEmpty ? '—' : value, style: pw.TextStyle(fontSize: 9.5, fontWeight: pw.FontWeight.bold, color: _inkColor)),
          ],
        ),
      );

  static pw.Widget _buildPatientInfoTable(EcgRecordModel record) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(border: pw.Border.all(color: _borderColor), borderRadius: pw.BorderRadius.circular(6)),
      child: pw.Column(
        children: [
          pw.Row(children: [
            _infoField('PATIENT', record.patient.name),
            _infoField('ID', record.patient.patientId),
            _infoField('AGE / SEX', '${record.patient.age} / ${record.patient.sex}'),
          ]),
          pw.SizedBox(height: 8),
          pw.Row(children: [
            _infoField('RECORDED', _formatDate(record.dateTime)),
            _infoField('DEVICE', record.deviceName.isEmpty ? '—' : record.deviceName),
            _infoField('HEART RATE', record.hr.isEmpty ? '—' : '${record.hr} bpm'),
          ]),
        ],
      ),
    );
  }

  static pw.Widget _buildLeadGrid(EcgRecordModel record) {
    final rows = <pw.Widget>[];
    for (var r = 0; r < 4; r++) {
      rows.add(pw.Row(
        children: List.generate(3, (c) {
          final index = r * 3 + c;
          final leadName = index < EcgData.leadName.length ? EcgData.leadName[index] : '';
          final samples = index < record.leadData.length ? record.leadData[index] : const <double>[];
          return pw.Expanded(
            child: pw.Container(
              margin: const pw.EdgeInsets.all(2),
              height: 46,
              decoration: pw.BoxDecoration(border: pw.Border.all(color: _borderColor, width: 0.5)),
              child: pw.Stack(children: [
                pw.Positioned(top: 2, left: 3, child: pw.Text(leadName, style: pw.TextStyle(fontSize: 6, color: _mutedColor))),
                pw.Center(child: _tracePainter(samples, width: 150, height: 40)),
              ]),
            ),
          );
        }),
      ));
    }
    return pw.Column(children: rows);
  }

  static pw.Widget _buildRhythmStrip(EcgRecordModel record) {
    final samples = record.leadData.length > 1 ? record.leadData[1] : const <double>[];
    return pw.Container(
      height: 60,
      decoration: pw.BoxDecoration(border: pw.Border.all(color: _borderColor, width: 0.5)),
      child: pw.Center(child: _tracePainter(samples, width: 520, height: 54)),
    );
  }

  static pw.Widget _buildCalibrationFooter(EcgRecordModel record, StorageService storage) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text('${storage.xAxisScale} mm/s · 10 mm/mV · ${record.filter}',
            style: pw.TextStyle(fontSize: 8, color: _mutedColor)),
        pw.Text('Gain: ${record.gain}', style: pw.TextStyle(fontSize: 8, color: _mutedColor)),
      ],
    );
  }

  static pw.Widget _tracePainter(List<double> samples, {required double width, required double height}) {
    return pw.CustomPaint(
      size: PdfPoint(width, height),
      painter: (context, size) {
        if (samples.isEmpty) return;
        final midY = size.y / 2;
        final window = samples.length > 300 ? samples.sublist(samples.length - 300) : samples;
        final xScale = size.x / window.length;
        context.setStrokeColor(_inkColor);
        context.setLineWidth(0.6);
        context.moveTo(0, midY - window[0] * 14);
        for (var i = 1; i < window.length; i++) {
          context.lineTo(i * xScale, midY - window[i] * 14);
        }
        context.strokePath();
      },
    );
  }

  static String _formatDate(DateTime dt) {
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return '${dt.day} ${months[dt.month - 1]} ${dt.year}, ${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}';
  }
}
